### ISSUE TITLE
Reference link missing

### ISSUE THREAD

**Issue by jonesjr12** [jamesware/alleleFrequencyApp#1]
Would you please send me the reference for your manuscript which describes the methods and mathematical derivations behind the calculators?  When I click on the link on the home page, it says "Not Found".

Thanks,

Julie Jones
juliejones@ggc.org

**Comment by nickywhiff** [comment]
Hi Julie,
The links have now been fixed on the app pages. The URL is http://biorxiv.org/content/early/2016/09/02/073114
Thanks,
Nicky
