### ISSUE TITLE
Page grayed Out

### ISSUE THREAD

**Issue by cliffrad123** [jamesware/alleleFrequencyApp#4]
Hello,

Trying to use this website on IE11 and Google Chrome however page is grayed out.  Website is not being accessed via proxy.

Any ideas???

**Comment by mianasbat** [comment]
Hi Cliffrad123,
Thank you for logging the ticket. We are working to resolve the issue. It would be very helpful if you could send a screenshot of the grey screen you are getting.
Thanks.

**Comment by cliffrad123** [comment]
Screenshot:

[cid:image001.png@01D2FFC0.34311000]

Kind Regards,

Clifford David
Service Desk Analyst, ICT Department
Birmingham Women’s and Children’s NHS Foundation Trust
T: 0121 472 1377 (x8904) | E: Clifford.David@nhs.net<mailto:Clifford.David@nhs.net>

[cid:7F68E52EFFF7A842BC90B1FA197D2A81@ad1.nhs.net]
Visit our website to find out more about our new Trust: bwc.nhs.uk<http://www.bwc.nhs.uk/>

**Comment by mianasbat** [comment]
Dear Clifford David,
I believe your institution firewall blocked the screenshot from upload and it is not displayed. However, I have performed some changes. Could you please check it now? 
Could you also tell me the way you are accessing it like using ssl (https://cardiodb.org/allelefrequencyapp/) or plain (http http://cardiodb.org/allelefrequencyapp/) ?
Please try both ways. I believe it has something to do with security too.
I will be waiting for your response.
Many thanks
Mian.

**Comment by cliffrad123** [comment]
Hello,

We access the website via this link: http://cardiodb.org/allelefrequencyapp/.
I have checked it in Google Chrome and IE and it seems ok….. page does not grey out.  I will get the user to give it a quick test and I will get back to you.

Thanks for the help,

Kind Regards,

Clifford David
Service Desk Analyst, ICT Department
Birmingham Women’s and Children’s NHS Foundation Trust
T: 0121 472 1377 (x8904) | E: Clifford.David@nhs.net<mailto:Clifford.David@nhs.net>

[cid:7F68E52EFFF7A842BC90B1FA197D2A81@ad1.nhs.net]
Visit our website to find out more about our new Trust: bwc.nhs.uk<http://www.bwc.nhs.uk/>

**Comment by cliffrad123** [comment]
Hi All,

Just like to confirm that this issue has now been resolved…… Thanks for all the help.

Kind Regards,

Clifford David
Service Desk Analyst, ICT Department
Birmingham Women’s and Children’s NHS Foundation Trust
T: 0121 472 1377 (x8904) | E: Clifford.David@nhs.net<mailto:Clifford.David@nhs.net>

[cid:7F68E52EFFF7A842BC90B1FA197D2A81@ad1.nhs.net]
Visit our website to find out more about our new Trust: bwc.nhs.uk<http://www.bwc.nhs.uk/>

**Comment by mianasbat** [comment]
Dear Clifford David,
Thank you for logging the issue and acknowledging the resolution. Enjoy the app :)
Best regards
Mian
