### ISSUE TITLE
Inverse AF equal for 95% and 99% CI?

### ISSUE THREAD

**Issue by lfeliubadalo** [jamesware/alleleFrequencyApp#5]
Hi,
when I tried to calculate Inverse AF with your app at 95% and 99% CI, I found the same result for all the variants I tested. I paste (and attach) a table with some examples from the GnomAD 2.1.1 Non cancer DB:
Variant | Outbred   population with maximal allele frequency for the variant | allele   count for this population | Allele   Number for this population | number   of homozygotes | Allele   freq for this population | FilterAllele   Freq according to Cardiodb inverse AF at 95%CI, for this figures | FilterAllele   Freq according to Cardiodb inverse AF at 99%CI, for this figures
11-108106435-A-G | AFR | 158 | 23612 | 0 | 0.006692 | 0.0058406 | 0.0058406
11-108123551-C-T | AFR | 153 | 23556 | 0 | 0.006495 | 0.0056562 | 0.0056562
11-108175387-G-C | SAS | 190 | 30490 | 2 | 0.006232 | 0.005507 | 0.005507
11-108143331-T-C | SAS | 152 | 30516 | 1 | 0.004981 | 0.0043355 | 0.0043355
11-108119654-T-G | NFE | 264 | 114368 | 1 | 0.002308 | 0.0020797 | 0.0020797
11-108119667-A-G | AFR | 58 | 23216 | 0 | 0.002498 | 0.0019842 | 0.0019842
11-108196763-C-A | LAT | 51 | 35054 | 0 | 0.001455 | 0.0011367 | 0.0011367
11-108155132-G-A | NFE | 146 | 117988 | 0 | 0.001237 | 0.0010739 | 0.0010739
11-108150352-T-C | SAS | 38 | 30494 | 0 | 0.001246 | 0.0009332 | 0.0009332
11-108160480-T-G | LAT | 38 | 35080 | 0 | 0.001083 | 0.0008112 | 0.0008112
11-108160516-A-G | NFE | 109 | 117644 | 0 | 0.0009265 | 0.0007855 | 0.0007855
Could you explain why this happens?
Thank you very much in advance,
Lídia

[examples.xlsx](https://github.com/jamesware/alleleFrequencyApp/files/3377832/examples.xlsx)

**Comment by jamesware** [comment]
Thanks for the notification.
We will look into this, though it will be a few weeks due to travel commitments.
BW,
James

**Comment by jamesware** [comment]
Thank you again for flagging this.  I think you have identified a genuine problem, and that I have found the cause.  It appears that 90% & 95% are correct, but if you attempt to select a confidence >99% it still returns the 95% value.   I will just do some tests on the solution and aim to push updated code to the website shortly.  Many thanks.

**Comment by lfeliubadalo** [comment]
Thank you!
Lidia

________________________________
De: James Ware <notifications@github.com>
Enviado: jueves, 11 de junio de 2020 18:50
Para: jamesware/alleleFrequencyApp <alleleFrequencyApp@noreply.github.com>
Cc: FELIUBADALO ELORZA, MARIA LIDIA <lfeliubadalo@iconcologia.net>; Author <author@noreply.github.com>
Asunto: Re: [jamesware/alleleFrequencyApp] Inverse AF equal for 95% and 99% CI? (#5)


Thank you again for flagging this. I think you have identified a genuine problem, and that I have found the cause. It appears that 90% & 95% are correct, but if you attempt to select a confidence >99% it still returns the 95% value. I will just do some tests on the solution and aim to push updated code to the website shortly. Many thanks.

**Comment by lfeliubadalo** [comment]
But then, is the problem solved? I see the same results when I use the webpage http://cardiodb.org/allelefrequencyapp/

**Comment by jamesware** [comment]
Yes - the code is fixed and has been tested off-line, and it is being deployed.
