### ISSUE TITLE
how to get "Popmax Filtering AF" reported on gnomAD browser from webtool

### ISSUE THREAD

**Issue by ekarlins** [jamesware/alleleFrequencyApp#7]
I'm trying to use your web-based app to replicate the results shown on the gnomAD browser for "Popmax Filtering AF", and then I wanted to adjust the parameters from there. I can't seem to replicate the exact results, though. It seems like for gnomAD the only parameter in the alleleFrequencyApp that would change for each variant is "Reference population size (alleles)". Yet adjusting this parameter doesn't seem to change the "Maximum credible population AF" at all. What am I missing? Is there a way to get your app to exactly replicate the results on the gnomAD browser?

Thanks!
Eric

**Comment by jamesware** [comment]
Hi Eric,

If this is not working for you please could you give an example?
I am able to reproduce the browser results as shown below - I suspect the likeliest cause for an apparent mismatch is either not selecting the matching subpopulation, or not selecting the exomes/genomes subset of the data.  I hope the description below clarifies things:

If I navigate to the example variant on the gnomAD landing page (dataset v2.1.1)
   https://gnomad.broadinstitute.org/variant/1-55516888-G-GA

I see a variant that is seen in 121 exomes, and 156 genomes, total 277 alleles

![image](https://user-images.githubusercontent.com/8571700/84156497-7cc42380-aa61-11ea-9c4f-39eff570e464.png)

The Popmax Filtering AF (95% confidence) for the exome data set is 0.01338

If you mouseover this number you will see that this value comes from the African subpopulation

Scroll down to the "Population Frequencies" table on the same page

By default this combines data from exome & genome datasets, so there are 251 alleles in Africans, and a total of 277 alleles seen (AN = 159612)

To replicate the Popmax FAF for the exome data, reported above, you need to de-select Genomes from the tickbox below the table

![image](https://user-images.githubusercontent.com/8571700/84156834-e5ab9b80-aa61-11ea-8182-77db35e422d0.png)

Total alleles is now 121 (AN = 128230)

For the African population you will see AC=97, AN=6082.

If I enter these values into the calculator at https://www.cardiodb.org/allelefrequencyapp/

The FAF (95%) is reported as 0.0133818, reproducing the value reported in the browser.



If you have an example that is not behaving as expected please do ping us back.  Thanks,
James

**Comment by ekarlins** [comment]
Thanks @jamesware! I think I was confused and trying to use the wrong tool on your site. I can see how to calculate the Filter Allele Frequency using the "inverse AF" tool.

Eric
